<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.18.7" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="FirebaseAdmin" Version="3.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.24">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlMostashar.Application\Minicato.Application.csproj" />
    <ProjectReference Include="..\AlMostashar.Domain\Minicato.Domain.csproj" />
  </ItemGroup>

</Project>
