using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace AlMostashar.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class RemoveDbLocationLookupsAndAddBroadcastOrderingIndex : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ClientRequests_Cities_CityId",
                table: "ClientRequests");

            migrationBuilder.DropForeignKey(
                name: "FK_ClientRequests_Governorates_GovernorateId",
                table: "ClientRequests");

            migrationBuilder.DropTable(
                name: "Cities");

            migrationBuilder.DropTable(
                name: "Governorates");

            migrationBuilder.CreateIndex(
                name: "IX_ClientRequests_RequestType_Status_CreatedAt_Id",
                table: "ClientRequests",
                columns: new[] { "RequestType", "Status", "CreatedAt", "Id" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_ClientRequests_RequestType_Status_CreatedAt_Id",
                table: "ClientRequests");

            migrationBuilder.CreateTable(
                name: "Governorates",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    EnglishName = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    Name = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Governorates", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Cities",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    GovernorateId = table.Column<int>(type: "int", nullable: false),
                    EnglishName = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    Name = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Cities", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Cities_Governorates_GovernorateId",
                        column: x => x.GovernorateId,
                        principalTable: "Governorates",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.InsertData(
                table: "Governorates",
                columns: new[] { "Id", "EnglishName", "Name" },
                values: new object[,]
                {
                    { 1, "Cairo", "القاهرة" },
                    { 2, "Giza", "الجيزة" },
                    { 3, "Alexandria", "الأسكندرية" },
                    { 4, "Dakahlia", "الدقهلية" },
                    { 5, "Red Sea", "البحر الأحمر" },
                    { 6, "Beheira", "البحيرة" },
                    { 7, "Fayoum", "الفيوم" },
                    { 8, "Gharbiya", "الغربية" },
                    { 9, "Ismailia", "الإسماعلية" },
                    { 10, "Menofia", "المنوفية" },
                    { 11, "Minya", "المنيا" },
                    { 12, "Qaliubiya", "القليوبية" },
                    { 13, "New Valley", "الوادي الجديد" },
                    { 14, "Suez", "السويس" },
                    { 15, "Aswan", "اسوان" },
                    { 16, "Assiut", "اسيوط" },
                    { 17, "Beni Suef", "بني سويف" },
                    { 18, "Port Said", "بورسعيد" },
                    { 19, "Damietta", "دمياط" },
                    { 20, "Sharkia", "الشرقية" },
                    { 21, "South Sinai", "جنوب سيناء" },
                    { 22, "Kafr Al sheikh", "كفر الشيخ" },
                    { 23, "Matrouh", "مطروح" },
                    { 24, "Luxor", "الأقصر" },
                    { 25, "Qena", "قنا" },
                    { 26, "North Sinai", "شمال سيناء" },
                    { 27, "Sohag", "سوهاج" }
                });

            migrationBuilder.InsertData(
                table: "Cities",
                columns: new[] { "Id", "EnglishName", "GovernorateId", "Name" },
                values: new object[,]
                {
                    { 1, "15 May", 1, "15 مايو" },
                    { 2, "Al Azbakeyah", 1, "الازبكية" },
                    { 3, "Al Basatin", 1, "البساتين" },
                    { 4, "Tebin", 1, "التبين" },
                    { 5, "El-Khalifa", 1, "الخليفة" },
                    { 6, "El darrasa", 1, "الدراسة" },
                    { 7, "Aldarb Alahmar", 1, "الدرب الاحمر" },
                    { 8, "Zawya al-Hamra", 1, "الزاوية الحمراء" },
                    { 9, "El-Zaytoun", 1, "الزيتون" },
                    { 10, "Sahel", 1, "الساحل" },
                    { 11, "El Salam", 1, "السلام" },
                    { 12, "Sayeda Zeinab", 1, "السيدة زينب" },
                    { 13, "El Sharabeya", 1, "الشرابية" },
                    { 14, "Shorouk", 1, "مدينة الشروق" },
                    { 15, "El Daher", 1, "الظاهر" },
                    { 16, "Ataba", 1, "العتبة" },
                    { 17, "New Cairo", 1, "القاهرة الجديدة" },
                    { 18, "El Marg", 1, "المرج" },
                    { 19, "Ezbet el Nakhl", 1, "عزبة النخل" },
                    { 20, "Matareya", 1, "المطرية" },
                    { 21, "Maadi", 1, "المعادى" },
                    { 22, "Maasara", 1, "المعصرة" },
                    { 23, "Mokattam", 1, "المقطم" },
                    { 24, "Manyal", 1, "المنيل" },
                    { 25, "Mosky", 1, "الموسكى" },
                    { 26, "Nozha", 1, "النزهة" },
                    { 27, "Waily", 1, "الوايلى" },
                    { 28, "Bab al-Shereia", 1, "باب الشعرية" },
                    { 29, "Bolaq", 1, "بولاق" },
                    { 30, "Garden City", 1, "جاردن سيتى" },
                    { 31, "Hadayek El-Kobba", 1, "حدائق القبة" },
                    { 32, "Helwan", 1, "حلوان" },
                    { 33, "Dar Al Salam", 1, "دار السلام" },
                    { 34, "Shubra", 1, "شبرا" },
                    { 35, "Tura", 1, "طره" },
                    { 36, "Abdeen", 1, "عابدين" },
                    { 37, "Abaseya", 1, "عباسية" },
                    { 38, "Ain Shams", 1, "عين شمس" },
                    { 39, "Nasr City", 1, "مدينة نصر" },
                    { 40, "New Heliopolis", 1, "مصر الجديدة" },
                    { 41, "Masr Al Qadima", 1, "مصر القديمة" },
                    { 42, "Mansheya Nasir", 1, "منشية ناصر" },
                    { 43, "Badr City", 1, "مدينة بدر" },
                    { 44, "Obour City", 1, "مدينة العبور" },
                    { 45, "Cairo Downtown", 1, "وسط البلد" },
                    { 46, "Zamalek", 1, "الزمالك" },
                    { 47, "Kasr El Nile", 1, "قصر النيل" },
                    { 48, "Rehab", 1, "الرحاب" },
                    { 49, "Katameya", 1, "القطامية" },
                    { 50, "Madinty", 1, "مدينتي" },
                    { 51, "Rod Alfarag", 1, "روض الفرج" },
                    { 52, "Sheraton", 1, "شيراتون" },
                    { 53, "El-Gamaleya", 1, "الجمالية" },
                    { 54, "10th of Ramadan City", 1, "العاشر من رمضان" },
                    { 55, "Helmeyat Alzaytoun", 1, "الحلمية" },
                    { 56, "New Nozha", 1, "النزهة الجديدة" },
                    { 57, "Capital New", 1, "العاصمة الإدارية" },
                    { 58, "Giza", 2, "الجيزة" },
                    { 59, "Sixth of October", 2, "السادس من أكتوبر" },
                    { 60, "Cheikh Zayed", 2, "الشيخ زايد" },
                    { 61, "Hawamdiyah", 2, "الحوامدية" },
                    { 62, "Al Badrasheen", 2, "البدرشين" },
                    { 63, "Saf", 2, "الصف" },
                    { 64, "Atfih", 2, "أطفيح" },
                    { 65, "Al Ayat", 2, "العياط" },
                    { 66, "Al-Bawaiti", 2, "الباويطي" },
                    { 67, "ManshiyetAl Qanater", 2, "منشأة القناطر" },
                    { 68, "Oaseem", 2, "أوسيم" },
                    { 69, "Kerdasa", 2, "كرداسة" },
                    { 70, "Abu Nomros", 2, "أبو النمرس" },
                    { 71, "Kafr Ghati", 2, "كفر غطاطي" },
                    { 72, "Manshiyet Al Bakari", 2, "منشأة البكاري" },
                    { 73, "Dokki", 2, "الدقى" },
                    { 74, "Agouza", 2, "العجوزة" },
                    { 75, "Haram", 2, "الهرم" },
                    { 76, "Warraq", 2, "الوراق" },
                    { 77, "Imbaba", 2, "امبابة" },
                    { 78, "Boulaq Dakrour", 2, "بولاق الدكرور" },
                    { 79, "Al Wahat Al Baharia", 2, "الواحات البحرية" },
                    { 80, "Omraneya", 2, "العمرانية" },
                    { 81, "Moneeb", 2, "المنيب" },
                    { 82, "Bin Alsarayat", 2, "بين السرايات" },
                    { 83, "Kit Kat", 2, "الكيت كات" },
                    { 84, "Mohandessin", 2, "المهندسين" },
                    { 85, "Faisal", 2, "فيصل" },
                    { 86, "Abu Rawash", 2, "أبو رواش" },
                    { 87, "Hadayek Alahram", 2, "حدائق الأهرام" },
                    { 88, "Haraneya", 2, "الحرانية" },
                    { 89, "Hadayek October", 2, "حدائق اكتوبر" },
                    { 90, "Saft Allaban", 2, "صفط اللبن" },
                    { 91, "Smart Village", 2, "القرية الذكية" },
                    { 92, "Ard Ellwaa", 2, "ارض اللواء" },
                    { 93, "Abu Qir", 3, "ابو قير" },
                    { 94, "Al Ibrahimeyah", 3, "الابراهيمية" },
                    { 95, "Azarita", 3, "الأزاريطة" },
                    { 96, "Anfoushi", 3, "الانفوشى" },
                    { 97, "Dekheila", 3, "الدخيلة" },
                    { 98, "El Soyof", 3, "السيوف" },
                    { 99, "Ameria", 3, "العامرية" },
                    { 100, "El Labban", 3, "اللبان" },
                    { 101, "Al Mafrouza", 3, "المفروزة" },
                    { 102, "El Montaza", 3, "المنتزه" },
                    { 103, "Mansheya", 3, "المنشية" },
                    { 104, "Naseria", 3, "الناصرية" },
                    { 105, "Ambrozo", 3, "امبروزو" },
                    { 106, "Bab Sharq", 3, "باب شرق" },
                    { 107, "Bourj Alarab", 3, "برج العرب" },
                    { 108, "Stanley", 3, "ستانلى" },
                    { 109, "Smouha", 3, "سموحة" },
                    { 110, "Sidi Bishr", 3, "سيدى بشر" },
                    { 111, "Shads", 3, "شدس" },
                    { 112, "Gheet Alenab", 3, "غيط العنب" },
                    { 113, "Fleming", 3, "فلمينج" },
                    { 114, "Victoria", 3, "فيكتوريا" },
                    { 115, "Camp Shizar", 3, "كامب شيزار" },
                    { 116, "Karmooz", 3, "كرموز" },
                    { 117, "Mahta Alraml", 3, "محطة الرمل" },
                    { 118, "Mina El-Basal", 3, "مينا البصل" },
                    { 119, "Asafra", 3, "العصافرة" },
                    { 120, "Agamy", 3, "العجمي" },
                    { 121, "Bakos", 3, "بكوس" },
                    { 122, "Boulkly", 3, "بولكلي" },
                    { 123, "Cleopatra", 3, "كليوباترا" },
                    { 124, "Glim", 3, "جليم" },
                    { 125, "Al Mamurah", 3, "المعمورة" },
                    { 126, "Al Mandara", 3, "المندرة" },
                    { 127, "Moharam Bek", 3, "محرم بك" },
                    { 128, "Elshatby", 3, "الشاطبي" },
                    { 129, "Sidi Gaber", 3, "سيدي جابر" },
                    { 130, "North Coast/sahel", 3, "الساحل الشمالي" },
                    { 131, "Alhadra", 3, "الحضرة" },
                    { 132, "Alattarin", 3, "العطارين" },
                    { 133, "Sidi Kerir", 3, "سيدي كرير" },
                    { 134, "Elgomrok", 3, "الجمرك" },
                    { 135, "Al Max", 3, "المكس" },
                    { 136, "Marina", 3, "مارينا" },
                    { 137, "Mansoura", 4, "المنصورة" },
                    { 138, "Talkha", 4, "طلخا" },
                    { 139, "Mitt Ghamr", 4, "ميت غمر" },
                    { 140, "Dekernes", 4, "دكرنس" },
                    { 141, "Aga", 4, "أجا" },
                    { 142, "Menia El Nasr", 4, "منية النصر" },
                    { 143, "Sinbillawin", 4, "السنبلاوين" },
                    { 144, "El Kurdi", 4, "الكردي" },
                    { 145, "Bani Ubaid", 4, "بني عبيد" },
                    { 146, "Al Manzala", 4, "المنزلة" },
                    { 147, "tami al'amdid", 4, "تمي الأمديد" },
                    { 148, "aljamalia", 4, "الجمالية" },
                    { 149, "Sherbin", 4, "شربين" },
                    { 150, "Mataria", 4, "المطرية" },
                    { 151, "Belqas", 4, "بلقاس" },
                    { 152, "Meet Salsil", 4, "ميت سلسيل" },
                    { 153, "Gamasa", 4, "جمصة" },
                    { 154, "Mahalat Damana", 4, "محلة دمنة" },
                    { 155, "Nabroh", 4, "نبروه" },
                    { 156, "Hurghada", 5, "الغردقة" },
                    { 157, "Ras Ghareb", 5, "رأس غارب" },
                    { 158, "Safaga", 5, "سفاجا" },
                    { 159, "El Qusiar", 5, "القصير" },
                    { 160, "Marsa Alam", 5, "مرسى علم" },
                    { 161, "Shalatin", 5, "الشلاتين" },
                    { 162, "Halaib", 5, "حلايب" },
                    { 163, "Aldahar", 5, "الدهار" },
                    { 164, "Damanhour", 6, "دمنهور" },
                    { 165, "Kafr El Dawar", 6, "كفر الدوار" },
                    { 166, "Rashid", 6, "رشيد" },
                    { 167, "Edco", 6, "إدكو" },
                    { 168, "Abu al-Matamir", 6, "أبو المطامير" },
                    { 169, "Abu Homs", 6, "أبو حمص" },
                    { 170, "Delengat", 6, "الدلنجات" },
                    { 171, "Mahmoudiyah", 6, "المحمودية" },
                    { 172, "Rahmaniyah", 6, "الرحمانية" },
                    { 173, "Itai Baroud", 6, "إيتاي البارود" },
                    { 174, "Housh Eissa", 6, "حوش عيسى" },
                    { 175, "Shubrakhit", 6, "شبراخيت" },
                    { 176, "Kom Hamada", 6, "كوم حمادة" },
                    { 177, "Badr", 6, "بدر" },
                    { 178, "Wadi Natrun", 6, "وادي النطرون" },
                    { 179, "New Nubaria", 6, "النوبارية الجديدة" },
                    { 180, "Alnoubareya", 6, "النوبارية" },
                    { 181, "Fayoum", 7, "الفيوم" },
                    { 182, "Fayoum El Gedida", 7, "الفيوم الجديدة" },
                    { 183, "Tamiya", 7, "طامية" },
                    { 184, "Snores", 7, "سنورس" },
                    { 185, "Etsa", 7, "إطسا" },
                    { 186, "Epschway", 7, "إبشواي" },
                    { 187, "Yusuf El Sediaq", 7, "يوسف الصديق" },
                    { 188, "Hadqa", 7, "الحادقة" },
                    { 189, "Atsa", 7, "اطسا" },
                    { 190, "Algamaa", 7, "الجامعة" },
                    { 191, "Sayala", 7, "السيالة" },
                    { 192, "Tanta", 8, "طنطا" },
                    { 193, "Al Mahalla Al Kobra", 8, "المحلة الكبرى" },
                    { 194, "Kafr El Zayat", 8, "كفر الزيات" },
                    { 195, "Zefta", 8, "زفتى" },
                    { 196, "El Santa", 8, "السنطة" },
                    { 197, "Qutour", 8, "قطور" },
                    { 198, "Basion", 8, "بسيون" },
                    { 199, "Samannoud", 8, "سمنود" },
                    { 200, "Ismailia", 9, "الإسماعيلية" },
                    { 201, "Fayed", 9, "فايد" },
                    { 202, "Qantara Sharq", 9, "القنطرة شرق" },
                    { 203, "Qantara Gharb", 9, "القنطرة غرب" },
                    { 204, "El Tal El Kabier", 9, "التل الكبير" },
                    { 205, "Abu Sawir", 9, "أبو صوير" },
                    { 206, "Kasasien El Gedida", 9, "القصاصين الجديدة" },
                    { 207, "Nefesha", 9, "نفيشة" },
                    { 208, "Sheikh Zayed", 9, "الشيخ زايد" },
                    { 209, "Shbeen El Koom", 10, "شبين الكوم" },
                    { 210, "Sadat City", 10, "مدينة السادات" },
                    { 211, "Menouf", 10, "منوف" },
                    { 212, "Sars El-Layan", 10, "سرس الليان" },
                    { 213, "Ashmon", 10, "أشمون" },
                    { 214, "Al Bagor", 10, "الباجور" },
                    { 215, "Quesna", 10, "قويسنا" },
                    { 216, "Berkat El Saba", 10, "بركة السبع" },
                    { 217, "Tala", 10, "تلا" },
                    { 218, "Al Shohada", 10, "الشهداء" },
                    { 219, "Minya", 11, "المنيا" },
                    { 220, "Minya El Gedida", 11, "المنيا الجديدة" },
                    { 221, "El Adwa", 11, "العدوة" },
                    { 222, "Magagha", 11, "مغاغة" },
                    { 223, "Bani Mazar", 11, "بني مزار" },
                    { 224, "Mattay", 11, "مطاي" },
                    { 225, "Samalut", 11, "سمالوط" },
                    { 226, "Madinat El Fekria", 11, "المدينة الفكرية" },
                    { 227, "Meloy", 11, "ملوي" },
                    { 228, "Deir Mawas", 11, "دير مواس" },
                    { 229, "Abu Qurqas", 11, "ابو قرقاص" },
                    { 230, "Ard Sultan", 11, "ارض سلطان" },
                    { 231, "Banha", 12, "بنها" },
                    { 232, "Qalyub", 12, "قليوب" },
                    { 233, "Shubra Al Khaimah", 12, "شبرا الخيمة" },
                    { 234, "Al Qanater Charity", 12, "القناطر الخيرية" },
                    { 235, "Khanka", 12, "الخانكة" },
                    { 236, "Kafr Shukr", 12, "كفر شكر" },
                    { 237, "Tukh", 12, "طوخ" },
                    { 238, "Qaha", 12, "قها" },
                    { 239, "Obour", 12, "العبور" },
                    { 240, "Khosous", 12, "الخصوص" },
                    { 241, "Shibin Al Qanater", 12, "شبين القناطر" },
                    { 242, "Mostorod", 12, "مسطرد" },
                    { 243, "El Kharga", 13, "الخارجة" },
                    { 244, "Paris", 13, "باريس" },
                    { 245, "Mout", 13, "موط" },
                    { 246, "Farafra", 13, "الفرافرة" },
                    { 247, "Balat", 13, "بلاط" },
                    { 248, "Dakhla", 13, "الداخلة" },
                    { 249, "Suez", 14, "السويس" },
                    { 250, "Alganayen", 14, "الجناين" },
                    { 251, "Ataqah", 14, "عتاقة" },
                    { 252, "Ain Sokhna", 14, "العين السخنة" },
                    { 253, "Faysal", 14, "فيصل" },
                    { 254, "Aswan", 15, "أسوان" },
                    { 255, "Aswan El Gedida", 15, "أسوان الجديدة" },
                    { 256, "Drau", 15, "دراو" },
                    { 257, "Kom Ombo", 15, "كوم أمبو" },
                    { 258, "Nasr Al Nuba", 15, "نصر النوبة" },
                    { 259, "Kalabsha", 15, "كلابشة" },
                    { 260, "Edfu", 15, "إدفو" },
                    { 261, "Al-Radisiyah", 15, "الرديسية" },
                    { 262, "Al Basilia", 15, "البصيلية" },
                    { 263, "Al Sibaeia", 15, "السباعية" },
                    { 264, "Abo Simbl Al Siyahia", 15, "ابوسمبل السياحية" },
                    { 265, "Marsa Alam", 15, "مرسى علم" },
                    { 266, "Assiut", 16, "أسيوط" },
                    { 267, "Assiut El Gedida", 16, "أسيوط الجديدة" },
                    { 268, "Dayrout", 16, "ديروط" },
                    { 269, "Manfalut", 16, "منفلوط" },
                    { 270, "Qusiya", 16, "القوصية" },
                    { 271, "Abnoub", 16, "أبنوب" },
                    { 272, "Abu Tig", 16, "أبو تيج" },
                    { 273, "El Ghanaim", 16, "الغنايم" },
                    { 274, "Sahel Selim", 16, "ساحل سليم" },
                    { 275, "El Badari", 16, "البداري" },
                    { 276, "Sidfa", 16, "صدفا" },
                    { 277, "Bani Sweif", 17, "بني سويف" },
                    { 278, "Beni Suef El Gedida", 17, "بني سويف الجديدة" },
                    { 279, "Al Wasta", 17, "الواسطى" },
                    { 280, "Naser", 17, "ناصر" },
                    { 281, "Ehnasia", 17, "إهناسيا" },
                    { 282, "beba", 17, "ببا" },
                    { 283, "Fashn", 17, "الفشن" },
                    { 284, "Somasta", 17, "سمسطا" },
                    { 285, "Alabbaseri", 17, "الاباصيرى" },
                    { 286, "Mokbel", 17, "مقبل" },
                    { 287, "PorSaid", 18, "بورسعيد" },
                    { 288, "Port Fouad", 18, "بورفؤاد" },
                    { 289, "Alarab", 18, "العرب" },
                    { 290, "Zohour", 18, "حى الزهور" },
                    { 291, "Alsharq", 18, "حى الشرق" },
                    { 292, "Aldawahi", 18, "حى الضواحى" },
                    { 293, "Almanakh", 18, "حى المناخ" },
                    { 294, "Mubarak", 18, "حى مبارك" },
                    { 295, "Damietta", 19, "دمياط" },
                    { 296, "New Damietta", 19, "دمياط الجديدة" },
                    { 297, "Ras El Bar", 19, "رأس البر" },
                    { 298, "Faraskour", 19, "فارسكور" },
                    { 299, "Zarqa", 19, "الزرقا" },
                    { 300, "alsaru", 19, "السرو" },
                    { 301, "alruwda", 19, "الروضة" },
                    { 302, "Kafr El-Batikh", 19, "كفر البطيخ" },
                    { 303, "Azbet Al Burg", 19, "عزبة البرج" },
                    { 304, "Meet Abou Ghalib", 19, "ميت أبو غالب" },
                    { 305, "Kafr Saad", 19, "كفر سعد" },
                    { 306, "Zagazig", 20, "الزقازيق" },
                    { 307, "Al Ashr Men Ramadan", 20, "العاشر من رمضان" },
                    { 308, "Minya Al Qamh", 20, "منيا القمح" },
                    { 309, "Belbeis", 20, "بلبيس" },
                    { 310, "Mashtoul El Souq", 20, "مشتول السوق" },
                    { 311, "Qenaiat", 20, "القنايات" },
                    { 312, "Abu Hammad", 20, "أبو حماد" },
                    { 313, "El Qurain", 20, "القرين" },
                    { 314, "Hehia", 20, "ههيا" },
                    { 315, "Abu Kabir", 20, "أبو كبير" },
                    { 316, "Faccus", 20, "فاقوس" },
                    { 317, "El Salihia El Gedida", 20, "الصالحية الجديدة" },
                    { 318, "Al Ibrahimiyah", 20, "الإبراهيمية" },
                    { 319, "Deirb Negm", 20, "ديرب نجم" },
                    { 320, "Kafr Saqr", 20, "كفر صقر" },
                    { 321, "Awlad Saqr", 20, "أولاد صقر" },
                    { 322, "Husseiniya", 20, "الحسينية" },
                    { 323, "san alhajar alqablia", 20, "صان الحجر القبلية" },
                    { 324, "Manshayat Abu Omar", 20, "منشأة أبو عمر" },
                    { 325, "Al Toor", 21, "الطور" },
                    { 326, "Sharm El-Shaikh", 21, "شرم الشيخ" },
                    { 327, "Dahab", 21, "دهب" },
                    { 328, "Nuweiba", 21, "نويبع" },
                    { 329, "Taba", 21, "طابا" },
                    { 330, "Saint Catherine", 21, "سانت كاترين" },
                    { 331, "Abu Redis", 21, "أبو رديس" },
                    { 332, "Abu Zenaima", 21, "أبو زنيمة" },
                    { 333, "Ras Sidr", 21, "رأس سدر" },
                    { 334, "Kafr El Sheikh", 22, "كفر الشيخ" },
                    { 335, "Kafr El Sheikh Downtown", 22, "وسط البلد كفر الشيخ" },
                    { 336, "Desouq", 22, "دسوق" },
                    { 337, "Fooh", 22, "فوه" },
                    { 338, "Metobas", 22, "مطوبس" },
                    { 339, "Burg Al Burullus", 22, "برج البرلس" },
                    { 340, "Baltim", 22, "بلطيم" },
                    { 341, "Masief Baltim", 22, "مصيف بلطيم" },
                    { 342, "Hamol", 22, "الحامول" },
                    { 343, "Bella", 22, "بيلا" },
                    { 344, "Riyadh", 22, "الرياض" },
                    { 345, "Sidi Salm", 22, "سيدي سالم" },
                    { 346, "Qellen", 22, "قلين" },
                    { 347, "Sidi Ghazi", 22, "سيدي غازي" },
                    { 348, "Marsa Matrouh", 23, "مرسى مطروح" },
                    { 349, "El Hamam", 23, "الحمام" },
                    { 350, "Alamein", 23, "العلمين" },
                    { 351, "Dabaa", 23, "الضبعة" },
                    { 352, "Al-Nagila", 23, "النجيلة" },
                    { 353, "Sidi Brani", 23, "سيدي براني" },
                    { 354, "Salloum", 23, "السلوم" },
                    { 355, "Siwa", 23, "سيوة" },
                    { 356, "Marina", 23, "مارينا" },
                    { 357, "North Coast", 23, "الساحل الشمالى" },
                    { 358, "Luxor", 24, "الأقصر" },
                    { 359, "New Luxor", 24, "الأقصر الجديدة" },
                    { 360, "Esna", 24, "إسنا" },
                    { 361, "New Tiba", 24, "طيبة الجديدة" },
                    { 362, "Al ziynia", 24, "الزينية" },
                    { 363, "Al Bayadieh", 24, "البياضية" },
                    { 364, "Al Qarna", 24, "القرنة" },
                    { 365, "Armant", 24, "أرمنت" },
                    { 366, "Al Tud", 24, "الطود" },
                    { 367, "Qena", 25, "قنا" },
                    { 368, "New Qena", 25, "قنا الجديدة" },
                    { 369, "Abu Tesht", 25, "ابو طشت" },
                    { 370, "Nag Hammadi", 25, "نجع حمادي" },
                    { 371, "Deshna", 25, "دشنا" },
                    { 372, "Alwaqf", 25, "الوقف" },
                    { 373, "Qaft", 25, "قفط" },
                    { 374, "Naqada", 25, "نقادة" },
                    { 375, "Farshout", 25, "فرشوط" },
                    { 376, "Quos", 25, "قوص" },
                    { 377, "Arish", 26, "العريش" },
                    { 378, "Sheikh Zowaid", 26, "الشيخ زويد" },
                    { 379, "Nakhl", 26, "نخل" },
                    { 380, "Rafah", 26, "رفح" },
                    { 381, "Bir al-Abed", 26, "بئر العبد" },
                    { 382, "Al Hasana", 26, "الحسنة" },
                    { 383, "Sohag", 27, "سوهاج" },
                    { 384, "Sohag El Gedida", 27, "سوهاج الجديدة" },
                    { 385, "Akhmeem", 27, "أخميم" },
                    { 386, "Akhmim El Gedida", 27, "أخميم الجديدة" },
                    { 387, "Albalina", 27, "البلينا" },
                    { 388, "El Maragha", 27, "المراغة" },
                    { 389, "almunsha'a", 27, "المنشأة" },
                    { 390, "Dar AISalaam", 27, "دار السلام" },
                    { 391, "Gerga", 27, "جرجا" },
                    { 392, "Jahina Al Gharbia", 27, "جهينة الغربية" },
                    { 393, "Saqilatuh", 27, "ساقلته" },
                    { 394, "Tama", 27, "طما" },
                    { 395, "Tahta", 27, "طهطا" },
                    { 396, "Alkawthar", 27, "الكوثر" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Cities_GovernorateId_Name",
                table: "Cities",
                columns: new[] { "GovernorateId", "Name" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Governorates_Name",
                table: "Governorates",
                column: "Name",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_ClientRequests_Cities_CityId",
                table: "ClientRequests",
                column: "CityId",
                principalTable: "Cities",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_ClientRequests_Governorates_GovernorateId",
                table: "ClientRequests",
                column: "GovernorateId",
                principalTable: "Governorates",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
